### ISSUE TITLE
"Not Technically Provably Accurate"

### ISSUE THREAD

**Issue by ChrisRackauckas** [ntezak/RK4.jl#1]
Hey,
  I saw this package and was wondering why you would say that it's not provably accurate. RK4 would fall into a class of Strong Order 0.5 algorithms by Rossler's root tree analysis.

**Comment by ntezak** [comment]
Hi, I am far from an expert on SDEs but after reading up a little bit on this I would agree. Thank you for your package DifferentialEquations.jl It looks awesome!

**Comment by ChrisRackauckas** [comment]
Thanks. And thanks for this package. I used it early on for code inspiration. I forgot I even left this. Well, I'll close this and let you decide if this is worth updating on the README. Just wanted to make sure no one would be steered in the wrong direction (because I don't think there's another mention of this fact on the internet).
